Repository boostcampwm-2024/web16-JuGa, pull requests merged in 2024-11, with the labels that each got.

#47 [BE] 3.02 주식차트 정보 기능 구현 수정 #6
  BE/src/app.module.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-credentials.dto.ts
  BE/src/auth/user.repository.ts
  BE/src/koreaInvestment/interface/korea-investment.interface.ts
  BE/src/koreaInvestment/korea-investment.module.ts
  BE/src/koreaInvestment/korea-investment.service.ts
  BE/src/stock/enum/market-type.ts
  BE/src/stock/index/dto/stock-index-list-chart.element.dto.ts
  BE/src/stock/index/dto/stock-index-response-element.dto.ts
  BE/src/stock/index/dto/stock-index-response.dto.ts
  BE/src/stock/index/dto/stock-index-value-element.dto.ts
  BE/src/stock/index/dto/stock.index.list.element.dto.ts
  BE/src/stock/index/dto/stock.index.response.element.dto.ts
  BE/src/stock/index/interface/stock-index.interface.ts
  BE/src/stock/index/stock-index.controller.ts
  BE/src/stock/index/stock-index.module.ts
  BE/src/stock/index/stock-index.service.ts
  BE/src/stock/index/stock.index.service.ts
  BE/src/stock/topfive/interface/stock-topfive.interface.ts
  BE/src/stock/topfive/stock-topfive.controller.ts
  BE/src/stock/topfive/stock-topfive.module.ts
  BE/src/stock/topfive/stock-topfive.service.ts
  BE/src/util/get-full-URL.ts
  BE/src/util/get-header.ts
  BE/src/websocket/socket.gateway.ts
  BE/src/websocket/socket.service.ts
  BE/test/stock/index/stock.index.list.e2e-spec.ts
  BE/test/stock/index/stock.index.value.e2e-spec.ts
Labels: BE, REFACTORING

#46 Week01 마무리 배포 (11.08)
  FE/.prettierrc.json
  FE/eslint.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/Logo.png
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/components/Login/Input.tsx
  FE/src/components/Login/index.tsx
  FE/src/components/StockIndex/Chart.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/TopFive/Card.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/components/TopFive/Nav.tsx
  FE/src/components/TopFive/SkeletonCard.tsx
  FE/src/components/TopFive/TopFive.tsx
  FE/src/components/TopFive/type.ts
  FE/src/main.tsx
  FE/src/page/Home.tsx
  FE/src/service/auth.ts
  FE/src/store/authStore.ts
  FE/src/store/useLoginModalStore.ts
  FE/src/types.ts
  FE/src/utils/chart.ts
Labels: FE, BE

#66 [FE] 주가 지수 정보 websocket 연동
  FE/package-lock.json
  FE/package.json
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/TopFive/type.ts
Labels: FE, INTEGRATION

#67 [FE] websocket 연결 단 한 번만 하도록 수정 #10
  FE/src/components/StockIndex/Card.tsx
  FE/src/socket.ts
Labels: FE, BUGFIX

#43 [BE] 2.04 oAuth를 활용한 로그인 API 구현 #7
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/dto/auth-credentials.dto.ts
  BE/src/auth/strategy/jwt.strategy.ts
  BE/src/auth/strategy/kakao.strategy.ts
  BE/src/auth/user.entity.ts
  BE/src/auth/user.repository.ts
  BE/src/configs/typeorm.config.ts
  BE/src/main.ts
  BE/src/types/express.d.ts
  BE/tsconfig.json
Labels: BE, API

#74 [FE] 로그인 실패 시 alert 문구 추가 #2
  FE/src/components/Login/index.tsx
Labels: FE, LAYOUT

#77 [FE] stock detail 페이지 레이아웃 구조 잡기
  FE/src/App.css
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/TradeSection.tsx
  FE/src/index.css
  FE/src/page/Home.tsx
  FE/src/page/StocksDetail.tsx
Labels: FE, LAYOUT

#76 [FE] 주가지수 차트 소켓 연결 & 그래프 수정 & 검색창 레이아웃 생성
  FE/src/components/Header.tsx
  FE/src/components/Login/index.tsx
  FE/src/components/Search/SearchHistoryItem.tsx
  FE/src/components/Search/SearchHistoryList.tsx
  FE/src/components/Search/SearchInput.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/TopFive/TopFive.tsx
  FE/src/page/Home.tsx
  FE/src/service/auth.ts
  FE/src/socket.ts
  FE/src/store/useSearchModalStore.ts
  FE/src/utils/ModalOveray.tsx
  FE/src/utils/chart.ts
Labels: FE, LAYOUT, INTEGRATION, REFACTORING

#78 [FE] 환경변수 이름 수정
  FE/src/components/TopFive/TopFive.tsx
Labels: FE, HOTFIX

#70 [BE] 7.03 매수 API 구현 #49
  BE/src/app.module.ts
  BE/src/auth/jwt-auth-guard.ts
  BE/src/stock/order/dto/stock-order-request.dto.ts
  BE/src/stock/order/enum/status-type.ts
  BE/src/stock/order/enum/trade-type.ts
  BE/src/stock/order/interface/request.interface.ts
  BE/src/stock/order/stock-order.controller.ts
  BE/src/stock/order/stock-order.entity.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/util/swagger.ts
Labels: BE, API

#71 [BE] 7.04 매도 API 구현 #50
  BE/src/stock/order/stock-order.controller.ts
  BE/src/stock/order/stock-order.service.ts
Labels: BE, API

#73 [BE] 7.05/7.06 매수/매도 예약 취소 API 구현 #51,#52
  BE/src/stock/order/stock-order.controller.ts
  BE/src/stock/order/stock-order.service.ts
Labels: BE, API

#75 [BE] 6.02 각 주식 정보 가져오기 API 구현
  BE/.eslintrc.js
  BE/src/app.module.ts
  BE/src/stock/detail/dto/stock-detail-output1.dto.ts
  BE/src/stock/detail/dto/stock-detail-output2.dto.ts
  BE/src/stock/detail/dto/stock-detail-query-parameter.dto.ts
  BE/src/stock/detail/dto/stock-detail-request.dto.ts
  BE/src/stock/detail/dto/stock-detail-response.dto.ts
  BE/src/stock/detail/interface/stock-detail.interface.ts
  BE/src/stock/detail/stock-detail.controller.ts
  BE/src/stock/detail/stock-detail.module.ts
  BE/src/stock/detail/stock-detail.service.ts
Labels: BE, API

#84 [BE] 소켓 코드 리팩터링
  BE/src/stock/order/stock-order.service.ts
  BE/src/websocket/base-socket.service.ts
  BE/src/websocket/socket-token.service.ts
  BE/src/websocket/socket.module.ts
  BE/src/websocket/socket.service.ts
  BE/src/websocket/stock-index-socket.service.ts
Labels: BE, REFACTORING

#87 [FE] 주식 상세보기 페이지 매매 현황판 레이아웃 생성
  FE/src/App.tsx
  FE/src/components/Login/index.tsx
  FE/src/components/ModalOveray.tsx
  FE/src/components/Search/SearchHistoryItem.tsx
  FE/src/components/Search/SearchHistoryList.tsx
  FE/src/components/Search/SearchInput.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceTableColumn.tsx
  FE/src/components/StocksDetail/PriceTableDayCard.tsx
  FE/src/components/StocksDetail/PriceTableLiveCard.tsx
  FE/src/components/TopFive/Card.tsx
  FE/src/utils/socket.ts
Labels: FE, LAYOUT

#88 [FE] 주식 차트 그리기 (라인 차트, bar 차트, 캔들 차트)
  FE/src/components/Login/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/dummy.ts
  FE/src/page/StocksDetail.tsx
Labels: FE, LAYOUT

#91 [BE] socket 분리 로직 수정
  BE/src/stock/index/stock-index.module.ts
  BE/src/stock/order/stock-order.controller.ts
  BE/src/websocket/base-socket.service.ts
  BE/src/websocket/socket.module.ts
  BE/src/websocket/stock-index-socket.service.ts
Labels: BE, BUGFIX

#92 [BE] 6.04 매수/매도 요청 현황 API 구현
  BE/src/app.module.ts
  BE/src/stock/trade/history/dto/stock-trade-history-data.dto.ts
  BE/src/stock/trade/history/dto/stock-trade-history-output.dto.ts
  BE/src/stock/trade/history/dto/stock-trade-history-query-parameter.dto.ts
  BE/src/stock/trade/history/dto/stock-trade-history-response.dto.ts
  BE/src/stock/trade/history/interface/Inquire-ccnl.interface.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
  BE/src/stock/trade/history/stock-trade-history.module.ts
  BE/src/stock/trade/history/stock-trade-history.service.ts
Labels: BE, API

#93 [BE] 5.03 주식 리스트 가져오기 API 구현
  BE/src/app.module.ts
  BE/src/stock/list/dto/stock-list-response.dto.ts
  BE/src/stock/list/interface/search-params.interface.ts
  BE/src/stock/list/stock-list.controller.ts
  BE/src/stock/list/stock-list.entity.ts
  BE/src/stock/list/stock-list.module.ts
  BE/src/stock/list/stock-list.repostiory.ts
  BE/src/stock/list/stock-list.service.ts
  scripts/stock-list.script.py
Labels: BE, API

#96 [BE] 소켓 로그 추가
  BE/src/websocket/base-socket.service.ts
  BE/src/websocket/socket.gateway.ts
Labels: BE, REFACTORING

#100 [FE] 검색 API 연동 & 검색 레이아웃 수정 & 거래 현황 API 연동
  FE/package-lock.json
  FE/package.json
  FE/public/searchAnimation.json
  FE/src/components/Header.tsx
  FE/src/components/Search/SearchCard.tsx
  FE/src/components/Search/SearchCardHighlight.tsx
  FE/src/components/Search/SearchList.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/Search/searchDataType.ts
  FE/src/components/StocksDetail/PriceDataType.ts
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceTableColumn.tsx
  FE/src/components/StocksDetail/PriceTableLiveCard.tsx
  FE/src/service/searchApi.ts
  FE/src/utils/useDebounce.ts
Labels: FE, LAYOUT, INTEGRATION

#102 [FE] 차트 디자인 개선 및 리팩토링
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/page/StocksDetail.tsx
  FE/src/types.ts
  FE/src/utils/chart.ts
Labels: FE, LAYOUT, REFACTORING

#99 [BE] 6.02 각 주식 정보 가져오기 API 구현 #54
  BE/src/stock/detail/dto/stock-detail-chart-data.dto.ts
  BE/src/stock/detail/dto/stock-detail-chart-request.dto.ts
  BE/src/stock/detail/dto/stock-detail-chart-response.dto.ts
  BE/src/stock/detail/dto/stock-detail-output1.dto.ts
  BE/src/stock/detail/dto/stock-detail-query-parameter.dto.ts
  BE/src/stock/detail/dto/stock-detail-response.dto.ts
  BE/src/stock/detail/interface/stock-detail-chart.interface.ts
  BE/src/stock/detail/interface/stock-detail.interface.ts
  BE/src/stock/detail/stock-detail.controller.ts
  BE/src/stock/detail/stock-detail.service.ts
Labels: BE, API, REFACTORING

#101 [BE] 6.04 매수/매도 요청 현황 API 구현
  BE/src/stock/trade/history/dto/daily-stock-trade-history-data.dto.ts
  BE/src/stock/trade/history/dto/daily-stock-trade-history-ouput.dto.ts
  BE/src/stock/trade/history/dto/daily-stock-trade-history-response.dto.ts
  BE/src/stock/trade/history/dto/stock-trade-history-query-parameter.dto.ts
  BE/src/stock/trade/history/dto/stock-trade-history-response.dto.ts
  BE/src/stock/trade/history/dto/today-stock-trade-history-data.dto.ts
  BE/src/stock/trade/history/dto/today-stock-trade-history-output.dto.ts
  BE/src/stock/trade/history/dto/today-stock-trade-history-response.dto.ts
  BE/src/stock/trade/history/interface/inquire-daily-price.interface.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
  BE/src/stock/trade/history/stock-trade-history.service.ts
Labels: BE, API

#98 [BE] 7.07 거래 체결 기능 구현 (WebSocket) #53
  BE/src/asset/asset.controller.ts
  BE/src/asset/asset.entity.ts
  BE/src/asset/asset.module.ts
  BE/src/asset/asset.repository.ts
  BE/src/asset/asset.service.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/user.repository.ts
  BE/src/stock/index/stock-index-socket.service.ts
  BE/src/stock/index/stock-index.module.ts
  BE/src/stock/order/dto/stock-order-request.dto.ts
  BE/src/stock/order/stock-order-socket.service.ts
  BE/src/stock/order/stock-order.entity.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/websocket/base-socket.service.ts
  BE/src/websocket/socket.module.ts
Labels: BE, SOCKET

#104 [FE] 6.06 주식 상세 정보 API 연동
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/page/StocksDetail.tsx
  FE/src/service/stocks.ts
  FE/src/types.ts
  FE/src/utils/chart.ts
Labels: FE, INTEGRATION

#110 [FE] stock detail 페이지 trade section 레이아웃 구성
  FE/public/emptyAnimation.json
  FE/src/components/Header.tsx
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/StocksDetail/TradeSection.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/components/TopFive/TopFive.tsx
Labels: FE, LAYOUT

#106 [BE] 소켓 연결 끊기는 현상 수정
  BE/src/websocket/base-socket.service.ts
Labels: BE, BUGFIX

#107 [BE] 6.02 각 주식 정보 가져오기 API 구현 #54
  BE/src/stock/detail/stock-detail.entity.ts
  BE/src/stock/detail/stock-detail.module.ts
  BE/src/stock/detail/stock-detail.repository.ts
  BE/src/stock/detail/stock-detail.service.ts
Labels: BE, API

#113 [BE] 7.07 거래 체결 기능 구현 (WebSocket) #53
  BE/src/stock/order/stock-order-socket.service.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/userStock/user-stock.controller.ts
  BE/src/userStock/user-stock.entity.ts
  BE/src/userStock/user-stock.module.ts
  BE/src/userStock/user-stock.repository.ts
  BE/src/userStock/user-stock.service.ts
Labels: BE, SOCKET

#128 [FE] 25.06 Nginx로 서버 구축 및 SSL 적용
  BE/src/main.ts
  FE/Dockerfile
  FE/nginx/nginx.conf
Labels: BE, API

#141 [FE] 주식 거래 페이지 구현
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/TradeSection.tsx
  FE/src/page/StocksDetail.tsx
Labels: FE, LAYOUT

#140 [FE] 그래프 고도화 작업(1) & SSE 연결 로직 구현
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceSectionSseHook.ts
  FE/src/utils/chart.ts
Labels: FE, LAYOUT

#129 [BE] 25.01 SSE 방식으로 거래체결내역 전달하기
  BE/src/stock/trade/history/interface/sse-event.ts
  BE/src/stock/trade/history/stock-trade-history-socket.service.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
  BE/src/stock/trade/history/stock-trade-history.module.ts
  BE/src/util/get-full-URL.ts
  BE/src/websocket/socket.gateway.ts
Labels: BE, SOCKET

#131 [BE] 25.02 소켓 재연결 로직 구현 #126
  BE/src/websocket/base-socket.service.ts
Labels: BE, BUGFIX

#134 [BE] requestApi, domain-service 적용 리팩터링
  BE/src/app.module.ts
  BE/src/common/koreaInvestment/interface/korea-investment.interface.ts
  BE/src/common/koreaInvestment/korea-investment.domain-service.ts
  BE/src/common/koreaInvestment/korea-investment.module.ts
  BE/src/common/websocket/base-socket.domain-service.ts
  BE/src/common/websocket/interface/socket.interface.ts
  BE/src/common/websocket/socket-token.domain-service.ts
  BE/src/common/websocket/socket.gateway.ts
  BE/src/common/websocket/socket.module.ts
  BE/src/koreaInvestment/korea-investment.module.ts
  BE/src/stock/detail/stock-detail.module.ts
  BE/src/stock/detail/stock-detail.service.ts
  BE/src/stock/index/stock-index-socket.service.ts
  BE/src/stock/index/stock-index.controller.ts
  BE/src/stock/index/stock-index.module.ts
  BE/src/stock/index/stock-index.service.ts
  BE/src/stock/order/stock-order-socket.service.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/topfive/stock-topfive.module.ts
  BE/src/stock/topfive/stock-topfive.service.ts
  BE/src/stock/trade/history/stock-trade-history-socket.service.ts
  BE/src/stock/trade/history/stock-trade-history.module.ts
  BE/src/stock/trade/history/stock-trade-history.service.ts
  BE/src/websocket/socket.module.ts
Labels: BE, REFACTORING

#143 [BE] 매도/매수 시 종목 코드 isNotEmpty 확인 추가
  BE/src/stock/order/dto/stock-order-request.dto.ts
Labels: BE, BUGFIX

#147 ✨ feat: 주식 주문에 사용할 상한가, 하한가 추가#144
  BE/src/stock/detail/dto/stock-detail-response.dto.ts
  BE/src/stock/detail/stock-detail.service.ts
Labels: BE, API

#153 [FE] 매수 API 연동 & 거래 확인 모달 레이아웃 구현
  FE/src/components/StocksDetail/TradeAlertModal.tsx
  FE/src/components/StocksDetail/TradeSection.tsx
  FE/src/page/StocksDetail.tsx
  FE/src/service/stocks.ts
  FE/src/store/tradeAlertModalStore.ts
  FE/src/types.ts
Labels: FE, LAYOUT, INTEGRATION

#158 [FE] 차트 관련 코드 리펙토링 & X축, Y축 라벨 작업 & 격자 생성 & SSE 연동
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceSectionSseHook.ts
  FE/src/components/StocksDetail/useDimensionsHook.ts
  FE/src/components/TopFive/Card.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/components/TopFive/type.ts
  FE/src/utils/chart.ts
  FE/src/utils/chart/drawBarChart.ts
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawChart.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawLowerYAxis.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/chart/makeLabels.ts
Labels: FE, LAYOUT, INTEGRATION

#149 [BE] 매수가능(자산) 매도가능(개수) 조회 API 구현 #145
  BE/src/asset/asset.controller.ts
  BE/src/asset/asset.module.ts
  BE/src/asset/asset.service.ts
  BE/src/asset/user-stock.entity.ts
  BE/src/asset/user-stock.repository.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/userStock/user-stock.controller.ts
  BE/src/userStock/user-stock.module.ts
  BE/src/userStock/user-stock.service.ts
Labels: BE, API

#162 [FE] 로그인 방식 쿠키로 변경 & production dev mode 분리
  FE/package-lock.json
  FE/package.json
  FE/src/components/Login/index.tsx
  FE/src/components/StocksDetail/TradeAlertModal.tsx
  FE/src/components/StocksDetail/TradeSection.tsx
  FE/src/service/stocks.ts
  FE/vite.config.ts
Labels: FE, BUGFIX

#159 [BE] 8.05, 8.07 프로필 및 포트폴리오 API 구현 #150
  BE/src/asset/asset.controller.ts
  BE/src/asset/asset.module.ts
  BE/src/asset/asset.service.ts
  BE/src/asset/dto/asset-response.dto.ts
  BE/src/asset/dto/mypage-response.dto.ts
  BE/src/asset/dto/stock-element-response.dto.ts
  BE/src/asset/interface/user-stock.interface.ts
  BE/src/asset/user-stock.repository.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/dto/profile-response.dto.ts
  BE/src/auth/user.controller.ts
  BE/src/auth/user.entity.ts
  BE/src/auth/user.service.ts
  BE/src/stock/detail/stock-detail.module.ts
  BE/src/stock/order/dto/stock-order-element-response.dto.ts
  BE/src/stock/order/interface/request.interface.ts
  BE/src/stock/order/interface/stock-order-raw.interface.ts
  BE/src/stock/order/stock-order.controller.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
Labels: BE, API

#164 [FE] 차트 리펙토링 & 차트 사이즈 조절 기능 구현
  FE/src/App.tsx
  FE/src/assets/emptyAnimation.json
  FE/src/assets/noResultAnimation.json
  FE/src/assets/searchAnimation.json
  FE/src/components/Header.tsx
  FE/src/components/Search/SearchCard.tsx
  FE/src/components/Search/SearchHistoryItem.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceTableDayCard.tsx
  FE/src/components/StocksDetail/useDimensionsHook.ts
  FE/src/components/TopFive/Nav.tsx
  FE/src/components/TopFive/TopFive.tsx
  FE/src/page/Rank.tsx
  FE/src/types.ts
  FE/src/utils/chart/drawBarChart.ts
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawChartGrid.ts
  FE/src/utils/chart/drawLowerYAxis.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/chart/makeLabels.ts
  FE/src/utils/formatTime.ts
Labels: FE, LAYOUT

#167 [FE] mypage 페이지 구현
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/FallbackUI.tsx
  FE/src/components/Header.tsx
  FE/src/components/Login/index.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/AccountCondition.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/Mypage/Nav.tsx
  FE/src/main.tsx
  FE/src/page/MyPage.tsx
  FE/src/service/assets.ts
  FE/src/types.ts
  FE/src/utils/common.ts
Labels: FE, LAYOUT, INTEGRATION

#157 [BE] 9.02 랭킹 확인 API 구현 (#124)
  BE/src/app.module.ts
  BE/src/asset/asset.entity.ts
  BE/src/asset/asset.repository.ts
  BE/src/asset/asset.service.ts
  BE/src/auth/optional-auth-guard.ts
  BE/src/auth/strategy/jwt.strategy.ts
  BE/src/auth/user.entity.ts
  BE/src/common/redis/redis.domain-service.ts
  BE/src/ranking/dto/ranking-response.dto.ts
  BE/src/ranking/enum/sort-type.enum.ts
  BE/src/ranking/interface/ranking.interface.ts
  BE/src/ranking/ranking.controller.ts
  BE/src/ranking/ranking.module.ts
  BE/src/ranking/ranking.service.ts
  BE/src/types/express.d.ts
Labels: BE, API

#161 [BE] 25.05 socket과 sse 비교하기
  BE/src/common/websocket/socket.gateway.ts
  BE/src/stock/trade/history/stock-trade-history-socket.service.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
Labels: BE, SOCKET

#163 [BE] 6.02 각 주식 정보 가져오기 기능 구현 (WebSocket)
  BE/src/stock/trade/history/dto/stock-detail-socket-data.dto.ts
  BE/src/stock/trade/history/stock-trade-history-socket.service.ts
Labels: BE, SOCKET

#168 [BE] 마이페이지 및 주문 API 수정
  BE/src/asset/asset.controller.ts
  BE/src/asset/asset.service.ts
  BE/src/asset/dto/asset-response.dto.ts
  BE/src/stock/order/dto/stock-order-element-response.dto.ts
  BE/src/stock/order/stock-order.controller.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
Labels: BE, BUGFIX

#169 [BE] 🔧 fix : query 별로 응답이 아닌 한번의 요청에 두개의 랭킹 모두 응답하게 변경(#124)
  BE/src/ranking/dto/ranking-data.dto.ts
  BE/src/ranking/dto/ranking-response.dto.ts
  BE/src/ranking/dto/ranking-result.dto.ts
  BE/src/ranking/ranking.controller.ts
  BE/src/ranking/ranking.service.ts
Labels: BE, API

#194 [FE] 매도 API 연동 & 레이아웃 구현
  FE/src/components/Mypage/Order.tsx
  FE/src/components/StocksDetail/SellSection.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/StocksDetail/TradeSection/TradeAlertModal.tsx
  FE/src/components/StocksDetail/TradeSection/index.tsx
  FE/src/components/StocksDetail/dummy.ts
  FE/src/service/assets.ts
  FE/src/service/orders.ts
  FE/src/utils/common.ts
Labels: FE, LAYOUT, INTEGRATION

#196 [FE] staleTime옵션 추가 & 해더 버튼 클릭 이벤트 최적화 & 뉴스 레이아웃
  FE/src/components/Header.tsx
  FE/src/components/News/CardWithImage.tsx
  FE/src/components/News/CardWithoutImage.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/newsMockData.ts
  FE/src/components/Rank/RankCard.tsx
  FE/src/components/Rank/RankList.tsx
  FE/src/components/Rank/RankType.ts
  FE/src/components/Rank/bummyData.ts
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/TopFive/TopFive.tsx
  FE/src/page/Home.tsx
  FE/src/page/Rank.tsx
  FE/src/service/getRanking.ts
  FE/src/service/getStockIndex.ts
Labels: FE, LAYOUT, BUGFIX

#186 [BE] 26.06 마이페이지 웹소켓 구독 로직 추가 #180
  BE/src/asset/asset.controller.ts
  BE/src/asset/asset.module.ts
  BE/src/asset/asset.repository.ts
  BE/src/asset/asset.service.ts
  BE/src/asset/dto/stock-element-response.dto.ts
  BE/src/asset/user-stock.repository.ts
  BE/src/stock/order/stock-order-socket.service.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/stock/trade/history/stock-trade-history.module.ts
Labels: BE, SOCKET

#197 [BE] 11.03, 12.03, 13.03 종목 즐겨찾기 API 구현 #177, #178, #179
  BE/src/app.module.ts
  BE/src/stock/bookmark/dto/stock-bookmark-response,dto.ts
  BE/src/stock/bookmark/interface/bookmark.interface.ts
  BE/src/stock/bookmark/stock-bookmark.controller.ts
  BE/src/stock/bookmark/stock-bookmark.entity.ts
  BE/src/stock/bookmark/stock-bookmark.module.ts
  BE/src/stock/bookmark/stock-bookmark.repository.ts
  BE/src/stock/bookmark/stock-bookmark.service.ts
Labels: BE, API

#201 [BE] 즐겨찾기, 마이페이지 API 수정
  BE/src/asset/asset.entity.ts
  BE/src/asset/asset.repository.ts
  BE/src/asset/asset.service.ts
  BE/src/asset/user-stock.entity.ts
  BE/src/asset/user-stock.repository.ts
  BE/src/main.ts
  BE/src/ranking/ranking.service.ts
  BE/src/stock/bookmark/stock-bookmark.controller.ts
  BE/src/stock/bookmark/stock-bookmark.service.ts
  BE/src/stock/detail/dto/stock-detail-response.dto.ts
  BE/src/stock/detail/stock-detail.controller.ts
  BE/src/stock/detail/stock-detail.repository.ts
  BE/src/stock/detail/stock-detail.service.ts
Labels: BE, API

#202 [FE] 차트 고도화 & 뉴스 레이아웃 수정
  FE/src/components/News/Card.tsx
  FE/src/components/News/CardWithImage.tsx
  FE/src/components/News/CardWithoutImage.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/newsMockData.ts
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/utils/chart/drawLowerYAxis.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
Labels: FE, LAYOUT

#204 [FE] 주식 상세페이지 웹소켓 연결 & 거래창 UI 개선
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/CancleAlertModal.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/Mypage/Order.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/StocksDetail/TradeSection/TradeAlertModal.tsx
  FE/src/hooks/useOrder.ts
  FE/src/page/MyPage.tsx
  FE/src/page/StocksDetail.tsx
  FE/src/service/assets.ts
  FE/src/service/stocks.ts
  FE/src/service/user.ts
  FE/src/store/orderCancleAlertModalStore.ts
  FE/src/types.ts
Labels: FE, LAYOUT, INTEGRATION

#203 [BE] 10.03 뉴스 조회 API 구현 #181
  BE/src/app.module.ts
  BE/src/news/dto/news-data-output.dto.ts
  BE/src/news/dto/news-database-response.dto.ts
  BE/src/news/dto/news-response.dto.ts
  BE/src/news/interface/news-value.interface.ts
  BE/src/news/naver-api-domian.service.ts
  BE/src/news/news.controller.ts
  BE/src/news/news.entity.ts
  BE/src/news/news.module.ts
  BE/src/news/news.repository.ts
  BE/src/news/news.service.ts
Labels: BE, API

#200 [BE] 26.04 웹소켓 코드 수정 #182
  BE/src/asset/asset.module.ts
  BE/src/asset/asset.service.ts
  BE/src/common/websocket/socket.gateway.ts
  BE/src/stock/index/stock-index-socket.service.ts
  BE/src/stock/index/stock-index.module.ts
  BE/src/stock/order/stock-order-socket.service.ts
  BE/src/stock/order/stock-order.module.ts
  BE/src/stock/order/stock-order.repository.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/stock/trade/history/stock-trade-history-socket.service.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
  BE/src/stock/trade/history/stock-trade-history.module.ts
  BE/src/stock/trade/history/stock-trade-history.service.ts
  BE/src/stockSocket/base-stock-socket.domain-service.ts
  BE/src/stockSocket/stock-execute-order.repository.ts
  BE/src/stockSocket/stock-index-socket.service.ts
  BE/src/stockSocket/stock-price-socket.service.ts
  BE/src/stockSocket/stock-socket.module.ts
Labels: BE, SOCKET, REFACTORING

#205 [FE] 브랜치 병합
  FE/src/components/Header.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/CancleAlertModal.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/Mypage/Order.tsx
  FE/src/components/News/Card.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/newsMockData.ts
  FE/src/components/Rank/RankCard.tsx
  FE/src/components/Rank/RankList.tsx
  FE/src/components/Rank/RankType.ts
  FE/src/components/Rank/bummyData.ts
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/SellSection.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/StocksDetail/TradeSection/TradeAlertModal.tsx
  FE/src/components/StocksDetail/TradeSection/index.tsx
  FE/src/components/StocksDetail/dummy.ts
  FE/src/components/TopFive/TopFive.tsx
  FE/src/hooks/useOrder.ts
  FE/src/page/Home.tsx
  FE/src/page/MyPage.tsx
  FE/src/page/Rank.tsx
  FE/src/page/StocksDetail.tsx
  FE/src/service/assets.ts
  FE/src/service/getRanking.ts
  FE/src/service/getStockIndex.ts
  FE/src/service/orders.ts
  FE/src/service/stocks.ts
  FE/src/service/user.ts
  FE/src/store/orderCancleAlertModalStore.ts
  FE/src/types.ts
  FE/src/utils/chart/drawLowerYAxis.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/common.ts
Labels: FE

#207 [BE] 뉴스 데이터 반환 타입 변경
  BE/src/news/dto/news-data-output.dto.ts
  BE/src/news/dto/news-item-data.dto.ts
  BE/src/news/dto/news-response.dto.ts
  BE/src/news/news.controller.ts
  BE/src/news/news.service.ts
Labels: BE, API

#209 [BE] html에서 사용하는 특수문자 변경
  BE/src/news/news.service.ts
Labels: BE, API, BUGFIX

#210 [BE] 체결량이 많은 종목에 대해 주문 시 체결이 여러번 되는 문제 해결
  BE/src/stockSocket/stock-execute-order.repository.ts
  BE/src/stockSocket/stock-price-socket.service.ts
Labels: BE, HOTFIX

#219 [FE] mypage 데이터 실시간 갱신 & mypage UI 개선
  FE/src/components/Login/index.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/types.ts
  FE/src/utils/common.ts
Labels: FE, LAYOUT, INTEGRATION

#220 [FE] 차트 고도화 & 뉴스 API 연동 & 거래현황 소켓 연결
  FE/src/components/News/Card.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/NewsDataType.ts
  FE/src/components/Search/SearchCardHighlight.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceTableColumn.tsx
  FE/src/service/getNewsData.ts
  FE/src/types.ts
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/formatNoSpecialChar.ts
  FE/src/utils/formatTime.ts
  FE/src/utils/useDebounce.ts
Labels: FE, LAYOUT, INTEGRATION, BUGFIX

#221 [FE] 브랜치 병합
  FE/src/components/Login/index.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/News/Card.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/NewsDataType.ts
  FE/src/components/Search/SearchCardHighlight.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/PriceSection.tsx
  FE/src/components/StocksDetail/PriceTableColumn.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/service/getNewsData.ts
  FE/src/types.ts
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/common.ts
  FE/src/utils/formatNoSpecialChar.ts
  FE/src/utils/formatTime.ts
  FE/src/utils/useDebounce.ts
Labels: FE

#222 [FE] 즐겨찾기 관련 레이아웃 구현 및 API 연동
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/BookMark.tsx
  FE/src/components/Mypage/Nav.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/Toast.tsx
  FE/src/page/MyPage.tsx
  FE/src/service/bookmark.ts
  FE/src/types.ts
  FE/src/utils/useDebounce.ts
Labels: FE, LAYOUT, INTEGRATION

#223 [BE] 유저 닉네임 변경 API 추가
  BE/src/auth/dto/rename-user.dto.ts
  BE/src/auth/user.controller.ts
  BE/src/auth/user.service.ts
Labels: BE, API

#224 [BE] 회원가입시 기본 닉네임 설정
  BE/src/auth/user.repository.ts
  BE/src/auth/user.service.ts
Labels: BE, API

#226 [BE] 닉네임 유효성 검사 로직 추가
  BE/src/auth/user.service.ts
Labels: BE, API, REFACTORING

#225 [FE] 유저 닉네임 수정 레이아웃 구현 및 API 연동
  FE/src/components/Mypage/BookMark.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/hooks/useUser.ts
  FE/src/service/stocks.ts
  FE/src/service/user.ts
Labels: FE, LAYOUT, INTEGRATION

#228 [FE] 차트 고도화 & favicon & 화면 레이아웃 일부 수정.
  FE/index.html
  FE/src/assets/favicon.ico
  FE/src/assets/logo.png
  FE/src/assets/logo.webp
  FE/src/components/Header.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/TopFive/Card.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/service/stocks.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/chart/makeLabels.ts
Labels: FE, LAYOUT

#229 [FE] 브랜치 병합
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/favicon.ico
  FE/src/assets/logo.png
  FE/src/assets/logo.webp
  FE/src/components/Header.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/BookMark.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/Nav.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/Header.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/Toast.tsx
  FE/src/components/TopFive/Card.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/hooks/useUser.ts
  FE/src/page/MyPage.tsx
  FE/src/service/bookmark.ts
  FE/src/service/stocks.ts
  FE/src/service/user.ts
  FE/src/types.ts
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/chart/makeLabels.ts
  FE/src/utils/useDebounce.ts
Labels: FE
