Repository boostcampwm-2024/web16-JuGa, pull requests merged in 2024-12, with the labels that each got.

#236 [BE] 주가 지수 서비스 테스트 코드 작성
  BE/src/news/news.service.ts
  BE/src/stock/index/mockdata/stock.index.list.mockdata.ts
  BE/src/stock/index/mockdata/stock.index.value.mockdata.ts
  BE/src/stock/index/stock-index.service.ts
  BE/src/stock/index/stock.index.service.spec.ts
  BE/test/stock/index/stock.index.list.e2e-spec.ts
  BE/test/stock/index/stock.index.value.e2e-spec.ts
  FE/src/assets/favicon.ico
  README.md
Labels: BE, TEST, API

#235 [FE] 차트 확대 축소 기능 추가 & 이동 평균선 NaN 오류 해결 & Top5 localeScale 적용
  FE/package-lock.json
  FE/package.json
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/TopFive/Card.tsx
  FE/src/utils/chart/drawCandleChart.ts
  FE/src/utils/chart/drawChartGrid.ts
  FE/src/utils/chart/drawLineChart.ts
  FE/src/utils/chart/drawLowerYAxis.ts
  FE/src/utils/chart/drawUpperYAxis.ts
  FE/src/utils/chart/drawXAxis.ts
  FE/src/utils/chart/makeChartDataFlat.ts
Labels: FE, LAYOUT, BUGFIX

#240 [BE] 27.07 주가 지수 서비스 테스트 코드 작성 #237
  BE/src/stock/index/mockdata/stock-index-list.mockdata.ts
  BE/src/stock/index/mockdata/stock-index-value.mockdata.ts
  BE/src/stock/index/stock-index.service.spec.ts
  BE/src/stock/index/stock-index.service.ts
  BE/test/stock/index/stock.index.list.e2e-spec.ts
  BE/test/stock/index/stock.index.value.e2e-spec.ts
Labels: BE, TEST, API

#243 [BE] 27.07 급상승/급하락 상위 5개 종목 테스트 코드 작성 #237
  BE/src/stock/topfive/mockdata/stock-topfive-high.mockdata.ts
  BE/src/stock/topfive/mockdata/stock-topfive-low.mockdata.ts
  BE/src/stock/topfive/stock-topfive.service.spec.ts
Labels: BE, TEST, API

#245 [BE] 27.07 주식 주문 서비스 테스트 코드 작성 #237
  BE/src/stock/order/stock-order.service.spec.ts
Labels: BE, TEST, API

#248 [BE] 27.07 주식 detail 페이지 서비스 테스트 코드 작성 #237
  BE/src/stock/detail/mockdata/stock-detail-chart.mockdata.ts
  BE/src/stock/detail/mockdata/stock-detail.mockdata.ts
  BE/src/stock/detail/stock-detail.service.spec.ts
Labels: BE, TEST, API

#249 [BE] 27.07 자산 서비스 테스트 코드 작성 #237
  BE/src/asset/asset-service.spec.ts
Labels: BE, TEST, API

#252 [BE] 27.07 즐겨찾기 서비스 테스트 코드 작성 #237
  BE/src/stock/bookmark/stock-bookmark.service.spec.ts
Labels: BE, TEST, API

#251 [BE] 27.10 실시간 체결가 범위 확장 #250
  BE/src/asset/asset.service.ts
  BE/src/stock/order/stock-order.service.ts
  BE/src/stock/trade/history/stock-trade-history.controller.ts
  BE/src/stockSocket/stock-price-socket.service.ts
Labels: BE, SOCKET, REFACTORING

#257 [FE] 웹 최적화 & Suspense를 이용해 Skeleton UI 적용
  FE/package-lock.json
  FE/package.json
  FE/public/robots.txt
  FE/src/App.tsx
  FE/src/components/GlobalErrorFallback.tsx
  FE/src/components/Header.tsx
  FE/src/components/Mypage/Account.tsx
  FE/src/components/Mypage/AccountSkeleton.tsx
  FE/src/components/Mypage/BookMark.tsx
  FE/src/components/Mypage/BookMarkSkeleton.tsx
  FE/src/components/Mypage/CancelAlertModal.tsx
  FE/src/components/Mypage/MyInfo.tsx
  FE/src/components/Mypage/MyInfoSkeleton.tsx
  FE/src/components/Mypage/Order.tsx
  FE/src/components/Mypage/OrderSkeleton.tsx
  FE/src/components/News/News.tsx
  FE/src/components/News/NewsCardSkeleton.tsx
  FE/src/components/News/NewsSkeleton.tsx
  FE/src/components/Rank/RankingSkeleton.tsx
  FE/src/components/StockIndex/StockIndexSekleton.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/StocksDetail/Chart.tsx
  FE/src/components/StocksDetail/ChartSkeleton.tsx
  FE/src/components/StocksDetail/PriceSection/TableColumn.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/TopFive/List.tsx
  FE/src/components/TopFive/SkeletonCard.tsx
  FE/src/components/TopFive/SkeletonList.tsx
  FE/src/components/TopFive/index.tsx
  FE/src/hooks/useOrder.ts
  FE/src/hooks/useUser.ts
  FE/src/main.tsx
  FE/src/page/Home.tsx
  FE/src/page/MyPage.tsx
  FE/src/page/Rank.tsx
  FE/src/page/StocksDetail.tsx
Labels: FE, LAYOUT, REFACTORING

#259 [FE] 자잘한 버그 수정 & 즐겨찾기 페이지에서 취소 기능 추가
  FE/src/components/FallbackUI.tsx
  FE/src/components/Header.tsx
  FE/src/components/Mypage/BookMark.tsx
  FE/src/components/Mypage/MyStocksList.tsx
  FE/src/components/Mypage/Order.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/hooks/useBookmark.ts
  FE/src/service/auth.ts
Labels: FE, LAYOUT, BUGFIX

#263 [BE] 27.11 데이터베이스 인덱싱 #238
  BE/src/asset/asset.entity.ts
  BE/src/stock/bookmark/stock-bookmark.entity.ts
  BE/src/stock/order/stock-order.entity.ts
Labels: BE, REFACTORING

#264 [BE] ranking, auth, stock-list 서비스 테스트 코드 작성
  BE/src/auth/auth.service.spec.ts
  BE/src/ranking/ranking.service.spec.ts
  BE/src/ranking/ranking.service.ts
  BE/src/stock/list/stock-list.service.spec.ts
  BE/src/stock/list/stock-list.service.ts
Labels: BE, TEST

#262 [FE] 브랜치 병합
  FE/package-lock.json
  FE/package.json
  FE/src/components/Header.tsx
  FE/src/components/Loading.tsx
  FE/src/components/Mypage/Order.tsx
  FE/src/components/News/Card.tsx
  FE/src/components/News/News.tsx
  FE/src/components/Search/KoreanMapping.ts
  FE/src/components/Search/SearchCard.tsx
  FE/src/components/Search/index.tsx
  FE/src/components/StockIndex/Card.tsx
  FE/src/components/StockIndex/index.tsx
  FE/src/components/StocksDetail/PriceSection/index.tsx
  FE/src/components/StocksDetail/TradeSection/BuySection.tsx
  FE/src/components/StocksDetail/TradeSection/SellSection.tsx
  FE/src/components/TopFive/index.tsx
  FE/src/hooks/useOrder.ts
  FE/src/page/StocksDetail.tsx
Labels: FE
